base/app/app/shop/__init__.py
from app.shop.views import shop 

base/app/app/shop/views.py
import datetime

from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    g,
)
from flask_login import current_user, login_required

from app import db
from app.models import Goods, List, Item 


shop = Blueprint('shop', __name__)

@shop.before_request
def before_request():
    goods = Goods.query.all()
    g.three_goods = goods[-3:]

#send data to browser, then show all goods 
@shop.route('/goods_all')
def goods_all():
    goods = Goods.query.all()

    return render_template('shop/goods_all.html', goods=goods)

#user select goods and into goods page
#server get data from database and send it to browserver
# if any one list not complete, allow continue to add item
# if complete of list, make new List and store item
# finally, add data into database  
@shop.route('/goods_all/<name>', methods=["GET", "POST"])
def goods_all_item(name):
    goods = Goods.query.filter_by(name=name).first()
    
    if request.form:
        now = datetime.datetime.now()
        list_current = List.query.filter(List.user_id==current_user.id, List.complete_on==False).all()

        if list_current:

            item_add = Item(
                list_id = list_current[0].id,
                name = goods.name,
                price = goods.price,
                num = request.form['num'],
            )
            
            db.session.add(item_add)
            db.session.commit()

            return redirect(url_for('shop.goods_all')) 

        else: 

            list_add = List(
                user_id = current_user.id,
                buy_date = now.strftime("%Y-%m-%d %H:%M")
            )
            db.session.add(list_add)
            db.session.commit()
            
            item_add = Item(
                list_id = list_add.id,
                name = goods.name,
                price = goods.price,
                num = request.form['num'],
            )
            
            db.session.add(item_add)
            db.session.commit()

            return redirect(url_for('shop.goods_all')) 

    return render_template('shop/goods_item.html', goods=goods)

#server deliver data to browser, that data is belong to current user
#browser get dat and show on page
@shop.route('/order_sheet')
def order_sheet():
    if current_user.is_active:
        shop_list = List.query.filter_by(user_id=current_user.id).all()

    else:
        shop_list = None

    return render_template('shop/order_sheet.html', shop_list=shop_list)

#user select id that user want to checkout or read info
@shop.route('/order_status/<id>', methods=["GET", "POST"])
@login_required
def order_status(id):
    item = Item.query.all()
    order_id_status = Item.query.filter_by(list_id=id).all()

    if request.form:

        if request.form["ok"] == "ok":
            sum = 0

            for i in order_id_status:
                sum += i.price

            current_user.wallet -= sum
            order_id_status[0].list.complete_on = True
            db.session.commit()

        return redirect(url_for('shop.order_sheet'))

    return render_template('shop/order_status.html', order_id_status=order_id_status)

base/app/app/templates/shop/display_temp.html
{% macro goods_display(goods) %}

    <div class="col-sm-2">
        <a href="{{ url_for('shop.goods_all_item', name=goods.name) }}"><img src=" {{ goods.img_path }} " class="log"></a><br>
        <b>name:</b> {{ goods.name }}<br>
        <b>price:</b> {{ goods.price }}<br>
    </div>



{% endmacro %}
<!-- template present name, price, image or other things,
add new good and using this function can display item -->

{% macro order_sheet(sheet) %}

    <div class="row">
        <div class="col-sm-2">
            {{ sheet.users.username }}
        </div>
        <div class="col-sm-3">
            <a href="{{ url_for('shop.order_status', id=sheet.id) }}">{{ sheet.id }}</a>
        </div>
        <div class="col-sm-3">
            {{ sheet.buy_date}}
        </div>
        <div class="col-sm-2">
            {% if sheet.complete_on %}
                <b>complete</b>
            {% else %}
                <b>wait</b>
            {% endif %}
        </div>       
    </div>

{% endmacro %}
<!-- show order sheet status, id link to detailed menu -->

{% macro order_display_item(item) %}

<div class="row">
    <div class="col-sm-2">
        {{ item.name }}
    </div>
    <div class="col-sm-2">
        {{ item.price }}
    </div>
    <div class="col-sm-2">
        {{ item.num }}
    </div>
</div>

{% endmacro%}

base/app/app/templates/shop/goods_all.html
{% extends 'layouts/base.html' %}
{% from "shop/display_temp.html" import goods_display %}

{% block post %}

    <div class="container">
        <div class="row">

        {% for i in  goods %}

          {{ goods_display(i) }}

        {% endfor %}
        
        </div>

    </div>
    
{% endblock %}

<!-- using display function present every good of database on web -->

base/app/app/templates/shop/goods_item.html
{% extends 'layouts/base.html' %}

{% block post %}

<div class="container">

        <form method="POST">

            <div class="row">
                <div class="col-sm-3">
                    <h1><b>{{ goods.name }}</b></h1><br>
                    <img src=" {{ goods.img_path }} " class="log">
                    <h2>Price: {{ goods.price }}</h2><br>
                </div>

                <div class="colsm-3">
                    <h2>{{ goods.text }}</h2><br>
                </div>
                
            </div>

            <div class="row">
                <div class="col-sm-offset-5">

                    {% if current_user.is_active %}

                        <h3>amount</h3>
                        <input type="integer" name="num" value="">
                        <input class="btn" type="submit" value="add"> 

                    {% else %}

                        <h2>You must Login</h2>

                    {% endif %}

                </div>
            </div>

        </form>

</div>
    
{% endblock %}
<!-- show content of goods  -->

base/app/app/templates/shop/order_sheet.html
{% extends 'layouts/base.html' %}
{% from "shop/display_temp.html" import order_sheet %}

{% block post %}
    
        {% if current_user.is_active %}

            <div class="row">
                <h3><b>Order</b></h3>
            </div>

            <div class="row">
                <div class="col-sm-2">
                    <b>user</b>
                </div>
                <div class="col-sm-3">
                    <b>order number</b>
                </div>
                <div class="col-sm-3">
                    <b>date</b>
                </div>
                <div class="col-sm-2">
                    <b>status</b>
                </div>
            </div><hr />      

            <div>
                {% for i in shop_list %}
                {{ order_sheet(i) }}<br>
                {% endfor %}
            </div>

        {% else %}

            <h3>You must Login to receive information</h3>   

        {% endif %}

{% endblock %}
<!-- using display function present every good of database on web -->

base/app/app/templates/shop/order_status.html
{% extends 'layouts/base.html' %}
{% from "shop/display_temp.html" import order_display_item %}

{% block post %}
<div class="row">
    <h3>your wallet:  {{ current_user.wallet }}</h3>
</div>

<div class="row">

    <div class="col-sm-offset-1">

        <div class="col-sm-2">
            <h4>name</h4>
        </div>
        <div class="col-sm-2">
            <h4>price</h4>
        </div>
        <div class="col-sm-2">
            <h4>num</h4>
        </div>

    </div>

</div>
<hr />

<div class="row">
    <div class="col-sm-offset-1">

        {% for item in order_id_status %}
            {{ order_display_item(item) }}
        {% endfor %}

    </div>

</div>
<hr />

<div class="row">
    {% if order_id_status[0].list.complete_on %}

        <div class="col-sm-offset-7">
                <b>complete</b>
        </div>

    {% else %}

        <div class="col-sm-offset-7">

            <form action="" method="POST">
                <input type="checkbox" name="ok" value="ok" checked>Ok<br>
                <input type="submit" value="Checkout">
            </form>

        </div>

    {% endif %}    
</div>
<hr />

{% endblock %}

<!-- using display function present every good of database on web -->